### PR TITLE
Updating gts4lv pre-install instructions

### PR DESCRIPTION
**Pull request by missingcharacter**
Source: https://forum.xda-developers.com/t/rom-official-gts4lvwifi-10-lineageos-17-1.3972371/#post-81575811

These are minor but important steps to make the process more clear

### CODE REVIEW

**Comment by missingcharacter** [comment]
@npjohnson anything I should add or is this not worth adding?

**Comment by npjohnson** [comment]
This needs to go to gerrit, not to GitHub Pull requests, see contributing to gerrit page on the wiki and close this one pls

But the submission itself looks good!

**Comment by missingcharacter** [comment]
Thanks @npjohnson

**Comment by missingcharacter** [comment]
excuse the n00bness https://review.lineageos.org/c/LineageOS/lineage_wiki/+/316676

**Pull request closed without merging**
