### PR TITLE
Describe Sony's unlocking process in slightly more detail

### PR DESCRIPTION
**Pull request by mathisdt**
There was a link to Sony's unlock page but the description on how to use the generated code was missing. Maybe this description was on Sony's website in the past.

### CODE REVIEW

**Comment by luk1337** [comment]
image
image

**Comment by mathisdt** [comment]
Whoa, I missed that link on Sony's website. Or perhaps I glanced over it because I didn't need assistance, but there may be someone who does this for the first time. I think the extra line may be helpful, but it's up to you if you incorporate the change. Hope to help! :slightly_smiling_face:

**Comment by luk1337** [comment]
Well, we don't accept changes from github anyway. If you care, upload this change to http://review.lineageos.org/

**Comment by mathisdt** [comment]
OK, I'll push it there and close this PR. Thanks!

**Pull request closed without merging**
