### PR TITLE
Update Z00L Info

### PR DESCRIPTION
**Pull request by flurbius**
Hi, I currently own and use daily, my second phone of this model, the battery is definitely replaceable, in fact you can buy a replacement battery on ebay for US$12
https://www.ebay.com/itm/Replacement-Li-ion-Battery-C11P1424-for-Asus-ZenFone2-ZE551ML-ZE550ML-3000mAh-US/253347885081?hash=item3afcb5f019:g:tx0AAOSw~3paTydh

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@flurbius Close?

Please submit patches through LineageOS Gerrit

**Comment by flurbius** [comment]
It is a very small change, and I really dont have the setup required at the
moment.  My laptop can barely run Android studio.
I just noticed that the information on my phone model has one error (the
battery IS replaceable).  I have managed to install the nightly build of
14.1 on my phone anyway, I just submitted the change to notify someone of
the error.

Close the issue if you like, as Ive stated above - it is a minor error and
doesnt seem to cause any issues.

cheers and thanks for a great OS.

**Comment by ItzLevvie** [comment]
@flurbius You're the one who created this issue and have permissions to close this issue. I'm not a LineageOS "maintainers" and I doubt the "maintainers" would waste their time on closing issues.

**Comment by ItzLevvie** [comment]
Hey there, @flurbius!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
