### PR TITLE
Update lux.yml

### PR DESCRIPTION
**Pull request by aVe2000**
reworked recovery boot description

my first commit, i hope, everything's right here..

### CODE REVIEW

**Comment by aVe2000** [comment]
my first commit, i hope, everything's right here.

**Comment by bgcngm** [comment]
Send your patches through gerrit: http://wiki.lineageos.org/contributing.html.

**Comment by aVe2000** [comment]
what do you mean with this? Is your suggested way a better way or the only way? When the last, why tehre seems to be a web interface?

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at https://zifnab.net/~zifnab/wiki_dump/Howto:_Gerrit.html

Thanks!

**Pull request closed without merging**
