### PR TITLE
wiki: add workaround for booting into TWRP recovery

### PR DESCRIPTION
**Pull request by igalic**
we can use `fastboot boot`.

Change-Id: I0dff841ebc1fbddbf29e76296823a92192703375

### CODE REVIEW

**Comment by mkwardakov** [comment]
This is very useful and will definitely save time.

**Comment by jedie** [comment]
LineageOS doesn't merge pull requests. Submit your change requests through https://review.lineageos.org/ see: https://wiki.lineageos.org/contributing_wiki.html

Maybe you can discuss this on their subreddit: https://www.reddit.com/r/LineageOS/

I don't know why pull requests here on github is available :(

**Comment by igalic** [comment]
you can turn off issues on github, but you can't turn off pull requests, because pull requests are github's innovation, and turning them off would mean resorting to emailing patches around… like animals!

lineageOS does not email patches around. they use Gerrit, where patches can equally be ignored as here:
https://review.lineageos.org/c/LineageOS/lineage_wiki/+/219543

please forgive me for not linking these two earlier together.

**Comment by ItzLevvie** [comment]
Hey there, @igalic!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by igalic** [comment]
I'm aware.

now that https://review.lineageos.org/c/LineageOS/lineage_wiki/+/219543 is merged, I'll close this, too

**Pull request closed without merging**
