### PR TITLE
fix(espressowifi): start on recovery keys

### PR DESCRIPTION
**Pull request by oupala**
Espressowifi start on recovery with volume down + power keys.

### CODE REVIEW

**Comment by genesis331** [comment]
LineageOS doesn't merge pull requests. Submit your change requests through https://review.lineageos.org/ . Check this too: https://wiki.lineageos.org/contributing_wiki.html

**Comment by oupala** [comment]
Creating an account on gerrit seems to require a Google account, which I do not have, and which I do not want to have (that's why I'm running LineageOS and not the stock rom).

If having a Google account is the only way to contribute, you can close this pull request.

**Comment by oupala** [comment]
Is there a way to merge this pull request without having a Google account?

**Comment by jedie** [comment]
LineageOS doesn't merge pull requests. Submit your change requests through https://review.lineageos.org/ see: https://wiki.lineageos.org/contributing_wiki.html

Maybe you can discuss this on their subreddit: https://www.reddit.com/r/LineageOS/

I don't know why pull requests here on github is available :(

**Comment by ItzLevvie** [comment]
Hey there, @oupala!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by oupala** [comment]
As [I already commented on 31 Jul 2018](https://github.com/LineageOS/lineage_wiki/pull/96#issuecomment-409120467), creating an account on gerrit seems to require a Google account, which I do not have, and which I do not want to have (that's why I'm running LineageOS and not the stock rom).

If having a Google account is the only way to contribute, you can close this pull request.

So the main question is : is there a way to merge this pull request without having a Google account?

**Comment by ItzLevvie** [comment]
@oupala As you're the author of the issue, only you can close it, not me :)
And no it's not possible to merge this without a Google account.

**Comment by oupala** [comment]
Ok, it is a strange decision from LineageOS to require a Google account to contribute to LineageOS, which is an android rom with no link with Google...

**Pull request closed without merging**
